### ISSUE TITLE
Sample feedback: display-web-interstitial-ad/js

### ISSUE THREAD

**Issue by torstendunkel** [googleads/google-publisher-tag-samples#102] opened 2024-09-17 12:22 UTC
Hi,

this example doesn't seem to work anymore. 
The static adslots gets requested and rendered and the interstitial slot gets never requested. 
The <div class="status"></div> stays with "Interstitial is loading..." the whole time.

Tested on newest chrome 128.0.6613.120 and FF 129.0.2

Any suggestions? 

Thanks

**Comment by jimper** [comment] 2024-09-17 12:25
Hi @torstendunkel, is this perhaps the same issue as #101 ?

**Comment by torstendunkel** [comment] 2024-09-17 12:30
Hi Jon,

thanks for quick response.
Didn't see that issue. And I can confirm that missing consent for purpose 1
is causing this issue.

Best,
Torsten


Am Di., 17. Sept. 2024 um 14:25 Uhr schrieb Jon Imperiosi <
***@***.***>:

**Comment by jimper** [comment] 2024-09-30 01:36
Duplicate of #101

**Closed by jimper** 2024-09-30 01:36 UTC
Labels: documentation
